import { CardType } from "../_types/types";

export const cards: CardType[] = [
  {
    id: 0,
    name: "felfel",
    totalQuantity: 6,
    oneCoinPrice: 2,
    twoCoinPrice: null,
    threeCoinPrice: 4,
    fourCoinPrice: null,
  },
  {
    id: 1,
    name: "nokhodFarangi",
    totalQuantity: 7,
    oneCoinPrice: 2,
    twoCoinPrice: 3,
    threeCoinPrice: 5,
    fourCoinPrice: null,
  },
  {
    id: 2,
    name: "bademjan",
    totalQuantity: 8,
    oneCoinPrice: 2,
    twoCoinPrice: 4,
    threeCoinPrice: 5,
    fourCoinPrice: null,
  },
  {
    id: 3,
    name: "goje",
    totalQuantity: 9,
    oneCoinPrice: 2,
    twoCoinPrice: 4,
    threeCoinPrice: 6,
    fourCoinPrice: null,
  },
  {
    id: 4,
    name: "hendoone",
    totalQuantity: 10,
    oneCoinPrice: 3,
    twoCoinPrice: 4,
    threeCoinPrice: 5,
    fourCoinPrice: 7,
  },
  {
    id: 5,
    name: "kharboze",
    totalQuantity: 11,
    oneCoinPrice: 3,
    twoCoinPrice: 5,
    threeCoinPrice: 6,
    fourCoinPrice: 7,
  },
  {
    id: 6,
    name: "kadooTanbal",
    totalQuantity: 12,
    oneCoinPrice: 3,
    twoCoinPrice: 5,
    threeCoinPrice: 6,
    fourCoinPrice: 8,
  },
  {
    id: 7,
    name: "shalgham",
    totalQuantity: 13,
    oneCoinPrice: 3,
    twoCoinPrice: 5,
    threeCoinPrice: 7,
    fourCoinPrice: 8,
  },
  {
    id: 8,
    name: "havij",
    totalQuantity: 14,
    oneCoinPrice: 4,
    twoCoinPrice: 5,
    threeCoinPrice: 7,
    fourCoinPrice: 8,
  },
  {
    id: 9,
    name: "loobia",
    totalQuantity: 15,
    oneCoinPrice: 4,
    twoCoinPrice: 6,
    threeCoinPrice: 7,
    fourCoinPrice: 8,
  },
  {
    id: 10,
    name: "piaz",
    totalQuantity: 16,
    oneCoinPrice: 4,
    twoCoinPrice: 6,
    threeCoinPrice: 7,
    fourCoinPrice: 9,
  },
  {
    id: 11,
    name: "sibzamini",
    totalQuantity: 17,
    oneCoinPrice: 4,
    twoCoinPrice: 6,
    threeCoinPrice: 8,
    fourCoinPrice: 9,
  },
  {
    id: 12,
    name: "khiar",
    totalQuantity: 18,
    oneCoinPrice: 4,
    twoCoinPrice: 6,
    threeCoinPrice: 8,
    fourCoinPrice: 10,
  },
];
